Install libexpat and libsodium packages
Both these packages are required by the build process, for `exml` and `enacl` respectively:

```
==> exml (compile)
Compiled src/exml_event.erl
Compiled src/exml_query.erl
Compiled src/exml_stream.erl
Compiled src/exml.erl
Compiling c_src/exml_utils.c
In file included from c_src/exml_utils.c:1:0:
c_src/exml.h:9:19: fatal error: expat.h: No such file or directory
 #include <expat.h>
                   ^
compilation terminated.
ERROR: compile failed while processing /app/deps/exml: rebar_abort
==> cog
** (Mix) Could not compile dependency :exml, "/root/.mix/rebar" command failed. You can recompile this dependency with "mix deps.compile exml", update it with "mix deps.update exml" or clean it with "mix deps.clean exml"
```

```
==> enacl (compile)
make: Entering directory '/app/deps/enacl/c_src'
cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/lib/erlang/erts-7.1/include/ -I /usr/lib/erlang/lib/erl_interface-3.8/include  -c -o /app/deps/enacl/c_src/enacl_nif.o /app/deps/enacl/c_src/enacl_nif.c
/app/deps/enacl/c_src/enacl_nif.c:5:20: fatal error: sodium.h: No such file or directory
 #include <sodium.h>
                    ^
compilation terminated.
Makefile:63: recipe for target '/app/deps/enacl/c_src/enacl_nif.o' failed
make: *** [/app/deps/enacl/c_src/enacl_nif.o] Error 1
make: Leaving directory '/app/deps/enacl/c_src'
ERROR: Command [compile] failed!
==> cog
** (Mix) Could not compile dependency :enacl, "/root/.mix/rebar" command failed. You can recompile this dependency with "mix deps.compile enacl", update it with "mix deps.update enacl" or clean it with "mix deps.clean enacl"
ERROR: Service 'bot' failed to build: The command '/bin/sh -c mix deps.get && mix deps.compile' returned a non-zero code: 1
```